### ISSUE TITLE
Error: Script Failed HGTV

### ISSUE THREAD

**Issue by Erijarla** [learningit/plugin.video.hgtv#3]
From last few days I'm getting Script failed error while opening HGTV. Tried in different devices but getting the same error.
Attaching the log.
[kodi_Logs.txt](https://github.com/learningit/plugin.video.hgtv/files/95359/kodi_Logs.txt)

**Comment by learningit** [comment]
Please use the kodi.org forum for support issues.
http://forum.kodi.tv/showthread.php?tid=237173
